### ISSUE TITLE
Failure running eccv_demo

### ISSUE THREAD

**Issue by erupnik** [wilsonkl/SfM_Init#10]
Hi, 
I'm running into a failure while multiprocessing of 1DSfM. Below is my screen output. Can anyone help? Thanks in advance.

python scripts/eccv_demo.py datasets/NYC_Library/ datasets/NYC_Library/
[eccv_demo] Reading input files
[eccv_demo] Running global rotations solver
[eccv_demo] Making a translations problem
[eccv_demo] Running 1DSfM to remove outliers
[1DSfM] input problem with 30116 edges
[1DSfM] using threshold = 0.1
[1DSfM] using num samples = 48
Traceback (most recent call last):
  File "scripts/eccv_demo.py", line 102, in <module>
    sys.exit(run_pipeline())
  File "scripts/eccv_demo.py", line 66, in run_pipeline
    clean_trans_problem.run_1DSfM(verbose=True)
  File "/home/er/Documents/d_development/structureless_BA/SfM_Init/sfminit/transproblem.py", line 49, in run_1DSfM
    mask = oneDSfM(self.edges, self.poses, **kwargs)
  File "/home/er/Documents/d_development/structureless_BA/SfM_Init/sfminit/onedsfm.py", line 53, in oneDSfM
    results = mp.Pool(num_workers).map(pool_worker, pool_args)
  File "/home/er/anaconda3/envs/SfmInit/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/er/anaconda3/envs/SfmInit/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
TypeError: pool_worker() takes exactly 3 arguments (1 given)

**Comment by erupnik** [comment]
Hi @wilsonkl 
your fix worked beautifully. Thank you so much!
e
